feat: CI test run notebook

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,9 +4,12 @@ on:
   push:
     branches:
       - '**'
+  pull_request:
+    branches:
+      - '**'
 
 jobs:
-  build:
+  commit-message:
     runs-on: ubuntu-latest
 
     steps:
@@ -26,6 +29,26 @@ jobs:
       - name: Validate commit message
         run: |
           ./ci/check_commits.sh "$commit_message"
+
+  run-notebooks:
+    runs-on: ubuntu-latest
+    needs: commit-message
+
+    steps:
+      # Install Python and Jupyter
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.x'
+
+      # Run notebook tests
+      - name: Test Jupyter notebooks
+        run: |
+          set -e  # Make sure that the script fails on the first error
+          # Run all notebooks to verify they are working
+          for notebook in $(find . -name "*.ipynb"); do
+            jupyter nbconvert --to notebook --execute --inplace "$notebook" || exit 1
+          done
 
   # build-documentation:
   #   runs-on: ubuntu-latest
